# check https://github.com/BlueBubblesApp/bluebubbles-app/blob/3f659afcb06e0b5766b4f1fc74cabc98c9498359/snap/snapcraft.yaml#L34
name: panel
base: core24
platforms:
  amd64:
  arm64:

version: "0.1.1"
summary: A configurable panel application for data collection and presentation.
description: |
  Panel is a configurable panel application for data collection and presentation. It is intended for use with external data collection devices and services, and provides a simple and flexible way to display data in a variety of formats.

grade: stable
confinement: strict

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/webkit2gtk-4.1
  /usr/lib/panel:
    symlink: $SNAP/usr/lib/panel

apps:
  panel:
    command: usr/bin/panel
    command-chain:
      - bin/gpu-2404-wrapper
    desktop: usr/share/applications/panel.desktop
    extensions:
      - gnome
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/blas:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/lapack:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/samba:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/vdpau:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri
      ALWAYS_USE_PULSEAUDIO: "1"
    plugs:
      - home
      - browser-support
      - network
      - network-status
      - gsettings
      - desktop
      - opengl

package-repositories:
  - type: apt
    components: [main]
    suites: [noble]
    key-id: 78E1918602959B9C59103100F1831DDAFC42E99D
    url: http://ppa.launchpad.net/snappy-dev/snapcraft-daily/ubuntu

parts:
  build-app:
    plugin: dump
    build-snaps:
      - bun-js/latest/stable
      - rustup/latest/stable
    build-packages:
      - libwebkit2gtk-4.1-dev
      - build-essential
      - curl
      - wget
      - file
      - libxdo-dev
      - libssl-dev
      - libayatana-appindicator3-dev
      - librsvg2-dev
      - dpkg
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libayatana-appindicator3-1

    source: .

    override-build: |
      set -eu
      bun install
      rustup default stable
      bun run tauri build --bundles deb
      dpkg -x src-tauri/target/release/bundle/deb/*.deb $SNAPCRAFT_PART_INSTALL/
      sed -i -e "s|Icon=panel|Icon=/usr/share/icons/hicolor/32x32/apps/panel.png|g" $SNAPCRAFT_PART_INSTALL/usr/share/applications/panel.desktop

  gpu-2404:
    after:
      - build-app
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404 nvidia-2404
    prime:
      - bin/gpu-2404-wrapper
