name: CI

on:
  pull_request:
  push:
    branches: [main]

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  lint-js:
    name: Lint and test frontend code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libasound2-dev

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Install frontend dependencies
        run: bun install

      - name: Run bun lint
        run: bun run lint

  lint-rust:
    name: Lint and test rust code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libasound2-dev

      - name: Update Rust
        run: rustup update stable && rustup default stable

      - name: Run clippy
        run: |
          mkdir dist
          cargo clippy --all-targets --all-features --manifest-path src-tauri/Cargo.toml

      - name: Run cargo test
        run: cargo test --verbose --manifest-path src-tauri/Cargo.toml
